#!/usr/bin/env /usr/bin/ansible-playbook
---


  # Get the ip address of the container
- name: Get the containers ip address
  command: "{{ paths.weave }} dns-lookup {{ weave_name }}"
  register: result

- debug: var=result

- name: Return only the item
  set_fact:
    weave_result: "{{ result.stdout }}"

- debug: var=weave_result


