---

# Shut down weave
- name: Stop weave
  command: "{{ ansible_weave_paths.weave }} stop"

- name: Reset the IPAM db
  command: "{{ ansible_weave_paths.weave }} reset --force"

- name: Launch Weave with root host
  command: "{{ ansible_weave_paths.weave }} launch --ipalloc-init observer {{ weave_root_host }} --ipalloc-default-subnet {{ weave_cidr }}"
  when: weave_root_host is defined
  register: result

- name: Launch Weave without root host
  command: "{{ ansible_weave_paths.weave }} launch  --ipalloc-default-subnet {{ weave_cidr }} "
  when: weave_root_host is not defined
  register: result


- name: Wait for weave to stabilize
  pause:
    seconds: "{{ ansible_weave_params.launch_wait }}"