---

- name: Connect weave to {{ item }}
  command: "{{ ansible_weave_paths_weave }} connect {{ item }}"
  when: "item != 'localhost' and inventory_hostname == 'localhost'"
  with_items: "{{ weave_hosts | default([]) }}"
  register: result


