---

- name: Expose Weave ports
  command: "{{ ansible_weave_paths_weave }} expose"
  when: weave_expose_cidr is not defined
  register: result

- name: Expose Weave ports
  command: "{{ ansible_weave_paths_weave }} expose {{ weave_expose_cidr }}"
  when: weave_expose_cidr is defined
  register: result


