#!/usr/bin/env /usr/bin/ansible-playbook
---


  # Get the ip address of the container
- name: Get the ip address of {{ weave_name }}
  command: "{{ ansible_weave_paths.weave }} dns-lookup {{ weave_name }}"
  register: result


- name: Return only {{ result.stdout }}
  set_fact:
    weave_result: "{{ result.stdout }}"



