---

# Shut down weave
- name: Stop weave
  command: "{{ ansible_weave_paths_weave }} stop"

- name: Reset the IPAM db
  command: "{{ ansible_weave_paths_weave }} reset --force"

- name: Launch Weave with root host
  command: "{{ ansible_weave_paths_weave }} launch --ipalloc-init observer {{ weave_root_host }}"
  when: weave_root_host is defined
  register: result

- name: Launch Weave without root host
  command: "{{ ansible_weave_paths_weave }} launch "
  when: weave_root_host is not defined
  register: result


- name: Wait for weave to stabilize
  pause:
    seconds: "{{ ansible_weave_params.launch_wait }}"