---

- name: Create a custom network for weave
  include: roles/ansible_docker_utils/tasks/create_weave_network.yml
  vars:
    docker_name: "{{ weave_name }}"
    docker_cidr: "{{ weave_cidr }}"

- debug: var=weave_name